name: Update Keeper Costs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update Keeper Costs
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TOKEN_FILE: ${{ secrets.TOKEN_FILE }}
        PUBLIC_KEY_ID: ${{ secrets.PUBLIC_KEY_ID }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        SHOULD_UPDATE_TOKENS: ${{ secrets.SHOULD_UPDATE_TOKENS }}
      run : |
        python keeper_league/keeper_costs.py
    - name: Save Keeper Costs
      run: |
        git config --global user.name 'Travis Paquette'
        git config --global user.email 'hkyplyr@users.noreply.github.com'
        git add docs/keeper-costs.csv
        git commit -m "Update keeper costs" || echo "No changes to commit"
        git push